### ISSUE TITLE
Pretrained adversarially robust model

### ISSUE THREAD

**Issue by jakespringer** [jjhenkel/averloc#7]
Hello, I loved your paper and I am excited about it. I am a student and I am working on a similar project related to attacking models of code. I am interested in playing around with the robust adversarially trained code2seq model, but unfortunately I do not have the computational resources to train it myself in a reasonable amount of time. I was wondering if you would be willing to share your model? Feel free to email me at jspring1@swarthmore.edu. 
Thank you,

**Comment by jjhenkel** [comment]
Hey thanks for your interest!

I'm happy to share some pre-trained models. I tried uploading the set to dropbox this morning, but I'm out of space (~50gb of models). I'll ping you again here when I find a suitable place to upload them.

**Comment by jakespringer** [comment]
Thank you! I would be happy to pay the $12 it costs for a month of Dropbox Plus if that would help.

**Comment by jjhenkel** [comment]
Kind offer, but no need! I (finally) managed to get these all up on OneDrive. [Link is here.](https://uwprod-my.sharepoint.com/:f:/g/personal/henkel3_wisc_edu/Erz744FON11ApAjv5k6W8A0B2MBc920L8TgkNxGmRwiOfw?e=cmjXbL) My university's OneDrive settings force that link expire after 30 days, just so you know. 

Hopefully these work for you---I had to do a little bit of cleanup during upload, but I think everything is there!

**Comment by jakespringer** [comment]
Thank you! This helps me out a lot.
